version: '2'
services:
  php:
    image: yiisoftware/yii2-php:8.2-fpm-nginx
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    environment:
      PHP_ENABLE_XDEBUG: 1
    ports:
      - '8000:80'
